spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: e336c80dcca376a46f01
                        client-secret: 16baa3769a50f5905b6f319584f90a31d6e4b924
                        redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - user:email
                            - read:user
                provider:
                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user